language: python
python: 
  - "3.5"

install:
  - pip install -r requirements.txt
script:
  - pytest -v
  - pytest --cov
  - python3 -m pytest --cov Application.views --cov-report term-missing

after_success:
  - coveralls